import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pawanlal Ganesh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Wait, I am Backend developer.</h1>
        <h1 className={styles.title}>This is all I can build.</h1>
        <Link href={"https://www.github.com/theofficialgithubuser"}>
          <a>
            <Image
              src="/GitHub_Logo.png"
              alt="github"
              height={50}
              width={125}
              style={{ backgroundColor: "white" }}
            />
          </a>
        </Link>
      </main>
    </div>
  );
};

export default Home;
